"""Structured geometry specifications for explicit corner models."""

from __future__ import annotations

from typing import Any, Literal, Mapping

from pydantic import BaseModel, ConfigDict, Field, model_validator

from kinematics.core.enums import (
    ActuationType,
    ArbType,
    CornerSpringType,
    HeaveLinkType,
    PointID,
    SuspensionType,
    Units,
)
from kinematics.core.primitives.geometry import Point3
from kinematics.core.primitives.point_ref import Side
from kinematics.core.schema.config import SuspensionConfig

HardpointMap = dict[PointID, Point3]


class GeometrySpecBase(BaseModel):
    """Fields shared by every geometry specification."""

    model_config = ConfigDict(
        frozen=True,
        arbitrary_types_allowed=True,
        extra="forbid",
    )

    name: str = "unnamed"
    version: str = "0.0.0"
    units: Units = Units.MILLIMETERS
    type: SuspensionType
    config: SuspensionConfig


class CornerGeometrySpecBase(GeometrySpecBase):
    """Fields required by every explicitly sided corner geometry."""

    side: Side

    @model_validator(mode="after")
    def check_physical_side(self) -> "CornerGeometrySpecBase":
        """A corner must be declared as the physical left or right side."""
        if self.side == Side.CENTER:
            raise ValueError("Corner geometry side must be 'left' or 'right'.")
        return self


class MechanismSpecBase(BaseModel):
    """Strict base for one explicitly selected suspension mechanism."""

    model_config = ConfigDict(frozen=True, extra="forbid")


class ActuationSpec(MechanismSpecBase):
    """Selected corner actuation mechanism."""

    type: ActuationType


class CornerSpringSpec(MechanismSpecBase):
    """Selected corner spring mechanism."""

    type: CornerSpringType


class DoubleWishboneMechanismsSpec(MechanismSpecBase):
    """Mechanisms installed on one double-wishbone corner."""

    actuation: ActuationSpec
    spring: CornerSpringSpec

    @model_validator(mode="after")
    def check_implemented_combination(self) -> "DoubleWishboneMechanismsSpec":
        """Reject combinations whose physical connection is not implemented."""
        if (
            self.actuation.type is ActuationType.DIRECT
            and self.spring.type is CornerSpringType.TORSION_BAR
        ):
            raise ValueError("Direct torsion-bar actuation is not implemented yet")
        return self


class DoubleWishboneGeometrySpec(CornerGeometrySpecBase):
    """Double-wishbone corner with composed actuation and spring mechanisms."""

    type: Literal[SuspensionType.DOUBLE_WISHBONE] = SuspensionType.DOUBLE_WISHBONE
    actuation: ActuationSpec
    spring: CornerSpringSpec
    hardpoints: HardpointMap

    @model_validator(mode="after")
    def check_mechanisms(self) -> "DoubleWishboneGeometrySpec":
        """Validate the selected corner mechanism combination."""
        DoubleWishboneMechanismsSpec(
            actuation=self.actuation,
            spring=self.spring,
        )
        return self


class AxleHardpointsSpec(BaseModel):
    """Either one mirrored corner map or explicit left and right maps."""

    model_config = ConfigDict(
        frozen=True,
        arbitrary_types_allowed=True,
        extra="forbid",
    )

    points: HardpointMap | None = None
    side: Side | None = None
    left: HardpointMap | None = None
    right: HardpointMap | None = None
    center: HardpointMap = Field(default_factory=dict)

    @model_validator(mode="after")
    def check_mode(self) -> "AxleHardpointsSpec":
        """Require exactly one unambiguous axle hardpoint mode."""
        explicit = self.left is not None or self.right is not None
        if explicit:
            if self.points is not None:
                raise ValueError(
                    "Give either a mirror-mode 'points' block or explicit "
                    "'left'/'right' blocks, not both."
                )
            if self.left is None or self.right is None:
                raise ValueError(
                    "Explicit-mode axle hardpoints require both 'left' and "
                    "'right' blocks."
                )
            if self.side is not None:
                raise ValueError("Explicit axle hardpoints do not accept 'side'.")
        else:
            if self.points is None:
                raise ValueError(
                    "Axle hardpoints require a mirror-mode 'points' block "
                    "or explicit 'left'/'right' blocks."
                )
            if self.side is None:
                raise ValueError("Mirror-mode axle hardpoints require 'side'.")
            if self.side == Side.CENTER:
                raise ValueError("Mirror source side must be 'left' or 'right'.")
        return self

    @property
    def is_explicit(self) -> bool:
        """Whether both sides are specified instead of generated by mirroring."""
        return self.left is not None


class ArbSpec(MechanismSpecBase):
    """Selected axle anti-roll mechanism."""

    type: ArbType


class HeaveLinkSpec(MechanismSpecBase):
    """Selected axle heave-link mechanism."""

    type: HeaveLinkType


class DoubleWishboneAxleGeometrySpec(GeometrySpecBase):
    """Full axle with composed corner and shared axle mechanisms."""

    type: Literal[SuspensionType.DOUBLE_WISHBONE_AXLE] = (
        SuspensionType.DOUBLE_WISHBONE_AXLE
    )
    corner: DoubleWishboneMechanismsSpec
    anti_roll: ArbSpec
    heave_link: HeaveLinkSpec
    hardpoints: AxleHardpointsSpec

    @model_validator(mode="after")
    def check_axle_mechanisms(self) -> "DoubleWishboneAxleGeometrySpec":
        """Validate shared mechanisms against the selected corner actuation."""
        has_rocker = self.corner.actuation.type is ActuationType.PUSHROD_ROCKER
        if self.anti_roll.type in (ArbType.U_BAR, ArbType.T_BAR) and not has_rocker:
            raise ValueError(
                "The implemented anti-roll mechanism requires pushrod-rocker actuation"
            )
        if self.heave_link.type is HeaveLinkType.ROCKER_TO_ROCKER and not has_rocker:
            raise ValueError(
                "A rocker-to-rocker heave link requires pushrod-rocker actuation"
            )
        return self


GeometrySpec = DoubleWishboneGeometrySpec | DoubleWishboneAxleGeometrySpec


def parse_geometry_spec(data: Mapping[str, Any]) -> GeometrySpecBase:
    """Validate a raw mapping as the explicitly selected corner type."""
    if "type" not in data:
        raise ValueError("Geometry type not specified")

    normalized = dict(data)
    type_key = normalized["type"]
    from kinematics.core.suspensions.registry import get_suspension_definition

    definition = get_suspension_definition(type_key)
    if definition is None:
        raise ValueError(f"Unsupported geometry type: '{type_key}'")
    normalized["type"] = definition.type_key
    try:
        return definition.spec_type.model_validate(normalized)
    except Exception as error:
        raise ValueError(f"Invalid geometry specification: {error}") from error
