"""
Structured geometry specifications.

``GeometrySpec`` is the validated, transport-agnostic description of a
suspension geometry: one spec model per suspension type, discriminated on the
``type`` field. The same models back YAML files (via ``kinematics.io``) and
structured API requests. Turn a spec into a live suspension with
:func:`kinematics.suspensions.build.build_suspension`.
"""

from __future__ import annotations

from typing import Annotated, Any, Literal, Mapping, Union

from pydantic import BaseModel, ConfigDict, Field, TypeAdapter, model_validator

from kinematics.core.enums import Units
from kinematics.core.point_ref import Side
from kinematics.schema.coercion import CIPointID, CISide, CIUnits, PydanticPoint3
from kinematics.schema.config import SuspensionConfig

# A named-point map: keys coerce case-insensitively to PointID, values to Point3.
HardpointMap = dict[CIPointID, PydanticPoint3]


class _GeometrySpecBase(BaseModel):
    """Fields shared by every geometry spec."""

    model_config = ConfigDict(frozen=True, arbitrary_types_allowed=True)

    name: str = "unnamed"
    version: str = "0.0.0"
    units: CIUnits = Units.MILLIMETERS
    config: SuspensionConfig


class DoubleWishboneGeometrySpec(_GeometrySpecBase):
    """A single double-wishbone corner: a flat hardpoint map plus config."""

    type: Literal["double_wishbone"] = "double_wishbone"
    hardpoints: HardpointMap


class AxleHardpointsSpec(BaseModel):
    """
    Hardpoints block for an axle, in one of two modes.

    - **Mirror mode**: ``points`` describes one side (``side``, default left)
      and the other side is generated by reflecting through the XZ plane
      (``y -> -y``).
    - **Explicit mode**: ``left`` and ``right`` each give a full corner map.

    ``center`` holds shared, non-mirrored points (the ARB axis pair). Per-side
    maps may include ``DROPLINK_ARB``, the axle-only droplink ARB-end point.
    """

    model_config = ConfigDict(frozen=True, arbitrary_types_allowed=True)

    points: HardpointMap | None = None
    side: CISide = Side.LEFT
    mirror: bool = True
    left: HardpointMap | None = None
    right: HardpointMap | None = None
    center: HardpointMap = Field(default_factory=dict)

    @model_validator(mode="after")
    def check_mode(self) -> "AxleHardpointsSpec":
        explicit = self.left is not None or self.right is not None
        if explicit:
            if self.points is not None:
                raise ValueError(
                    "Give either a mirror-mode 'points' block or explicit "
                    "'left'/'right' blocks, not both."
                )
            if self.left is None or self.right is None:
                raise ValueError(
                    "Explicit-mode axle hardpoints require both 'left' and "
                    "'right' blocks."
                )
        else:
            if self.points is None:
                raise ValueError(
                    "Axle hardpoints require a mirror-mode 'points' block "
                    "or explicit 'left'/'right' blocks."
                )
            if not self.mirror:
                raise ValueError(
                    "Mirror-mode hardpoints with 'mirror: false' are ambiguous; "
                    "give both sides explicitly under 'left' and 'right'."
                )
            if self.side == Side.CENTER:
                raise ValueError("Mirror source side must be 'left' or 'right'.")
        return self

    @property
    def is_explicit(self) -> bool:
        """Whether both sides are given explicitly (vs. mirror mode)."""
        return self.left is not None


class DoubleWishboneAxleGeometrySpec(_GeometrySpecBase):
    """A full axle: two double-wishbone corners plus shared center points."""

    type: Literal["double_wishbone_axle"] = "double_wishbone_axle"
    hardpoints: AxleHardpointsSpec


GeometrySpec = Annotated[
    Union[DoubleWishboneGeometrySpec, DoubleWishboneAxleGeometrySpec],
    Field(discriminator="type"),
]

_GEOMETRY_SPEC_ADAPTER: TypeAdapter[
    DoubleWishboneGeometrySpec | DoubleWishboneAxleGeometrySpec
] = TypeAdapter(GeometrySpec)


def parse_geometry_spec(
    data: Mapping[str, Any],
) -> DoubleWishboneGeometrySpec | DoubleWishboneAxleGeometrySpec:
    """
    Validate a raw mapping into the matching geometry spec.

    The ``type`` key selects the spec model (case-insensitive).

    Raises:
        ValueError: If ``type`` is missing/unknown or validation fails.
    """
    if "type" not in data:
        raise ValueError("Geometry type not specified")

    normalized = dict(data)
    normalized["type"] = str(normalized["type"]).lower()
    try:
        return _GEOMETRY_SPEC_ADAPTER.validate_python(normalized)
    except Exception as e:
        raise ValueError(f"Invalid geometry specification: {e}") from e
