"""Structured geometry specifications for explicit corner models."""

from __future__ import annotations

from typing import Any, Literal, Mapping

from pydantic import BaseModel, ConfigDict, model_validator

from kinematics.core.enums import Units
from kinematics.core.point_ref import Side
from kinematics.schema.coercion import CIPointID, CISide, CIUnits, PydanticPoint3
from kinematics.schema.config import SuspensionConfig

HardpointMap = dict[CIPointID, PydanticPoint3]


class GeometrySpecBase(BaseModel):
    """Fields shared by every geometry specification."""

    model_config = ConfigDict(
        frozen=True,
        arbitrary_types_allowed=True,
        extra="forbid",
    )

    name: str = "unnamed"
    version: str = "0.0.0"
    units: CIUnits = Units.MILLIMETERS
    type: str
    config: SuspensionConfig


class CornerGeometrySpecBase(GeometrySpecBase):
    """Fields required by every explicitly sided corner geometry."""

    side: CISide

    @model_validator(mode="after")
    def check_physical_side(self) -> "CornerGeometrySpecBase":
        """A corner must be declared as the physical left or right side."""
        if self.side == Side.CENTER:
            raise ValueError("Corner geometry side must be 'left' or 'right'.")
        return self


class DoubleWishboneGeometrySpec(CornerGeometrySpecBase):
    """A basic double-wishbone corner."""

    type: Literal["double_wishbone"] = "double_wishbone"
    hardpoints: HardpointMap


class DoubleWishboneCoiloverGeometrySpec(CornerGeometrySpecBase):
    """A double-wishbone corner with a lower-wishbone-mounted coilover."""

    type: Literal["double_wishbone_coilover"] = "double_wishbone_coilover"
    hardpoints: HardpointMap


class AxleHardpointsSpec(BaseModel):
    """Either one mirrored corner map or explicit left and right maps."""

    model_config = ConfigDict(
        frozen=True,
        arbitrary_types_allowed=True,
        extra="forbid",
    )

    points: HardpointMap | None = None
    side: CISide = Side.LEFT
    left: HardpointMap | None = None
    right: HardpointMap | None = None

    @model_validator(mode="after")
    def check_mode(self) -> "AxleHardpointsSpec":
        """Require exactly one unambiguous axle hardpoint mode."""
        explicit = self.left is not None or self.right is not None
        if explicit:
            if self.points is not None:
                raise ValueError(
                    "Give either a mirror-mode 'points' block or explicit "
                    "'left'/'right' blocks, not both."
                )
            if self.left is None or self.right is None:
                raise ValueError(
                    "Explicit-mode axle hardpoints require both 'left' and "
                    "'right' blocks."
                )
        else:
            if self.points is None:
                raise ValueError(
                    "Axle hardpoints require a mirror-mode 'points' block "
                    "or explicit 'left'/'right' blocks."
                )
            if self.side == Side.CENTER:
                raise ValueError("Mirror source side must be 'left' or 'right'.")
        return self

    @property
    def is_explicit(self) -> bool:
        """Whether both sides are specified instead of generated by mirroring."""
        return self.left is not None


class DoubleWishboneAxleGeometrySpec(GeometrySpecBase):
    """A full axle composed from two basic double-wishbone corners."""

    type: Literal["double_wishbone_axle"] = "double_wishbone_axle"
    hardpoints: AxleHardpointsSpec


GeometrySpec = (
    DoubleWishboneGeometrySpec
    | DoubleWishboneCoiloverGeometrySpec
    | DoubleWishboneAxleGeometrySpec
)


def parse_geometry_spec(data: Mapping[str, Any]) -> GeometrySpecBase:
    """Validate a raw mapping as the explicitly selected corner type."""
    if "type" not in data:
        raise ValueError("Geometry type not specified")

    normalized = dict(data)
    type_key = str(normalized["type"]).lower()
    normalized["type"] = type_key
    from kinematics.suspensions.registry import get_suspension_definition

    definition = get_suspension_definition(type_key)
    if definition is None:
        raise ValueError(f"Unsupported geometry type: '{type_key}'")
    normalized["type"] = definition.type_key
    try:
        return definition.spec_type.model_validate(normalized)
    except Exception as error:
        raise ValueError(f"Invalid geometry specification: {error}") from error


__all__ = [
    "DoubleWishboneCoiloverGeometrySpec",
    "DoubleWishboneAxleGeometrySpec",
    "DoubleWishboneGeometrySpec",
    "AxleHardpointsSpec",
    "CornerGeometrySpecBase",
    "GeometrySpec",
    "GeometrySpecBase",
    "HardpointMap",
    "parse_geometry_spec",
]
