"""
Suspension construction from validated geometry specs.

:func:`build_suspension` is the single entry point for turning a validated
``GeometrySpec`` (see ``kinematics.schema.geometry``) into a live suspension
instance. Front-ends never construct suspension classes from raw mappings:
YAML files and API requests both validate into a spec first, then build here.
"""

from __future__ import annotations

from kinematics.core.enums import PointID, ShimType
from kinematics.core.geometry import Direction3, Point3
from kinematics.core.point_ref import PointKey, Side
from kinematics.schema.config import SuspensionConfig
from kinematics.schema.geometry import (
    DoubleWishboneAxleGeometrySpec,
    DoubleWishboneGeometrySpec,
)
from kinematics.suspensions.axle import DoubleWishboneAxleSuspension
from kinematics.suspensions.base import Suspension
from kinematics.suspensions.double_wishbone import DoubleWishboneSuspension


def build_suspension(
    spec: DoubleWishboneGeometrySpec | DoubleWishboneAxleGeometrySpec,
) -> Suspension:
    """
    Construct a suspension instance from a validated geometry spec.

    Args:
        spec: A validated geometry specification.

    Returns:
        The instantiated suspension.

    Raises:
        ValueError: If the spec's points are invalid for the suspension type,
            required hardpoints are missing, or a per-side sign check fails.
    """
    if isinstance(spec, DoubleWishboneGeometrySpec):
        return _build_corner(spec)
    if isinstance(spec, DoubleWishboneAxleGeometrySpec):
        return _build_axle(spec)
    raise TypeError(f"Unsupported geometry spec: {type(spec).__name__}")


def _build_corner(spec: DoubleWishboneGeometrySpec) -> DoubleWishboneSuspension:
    """Build a single double-wishbone corner."""
    cls = DoubleWishboneSuspension
    _check_valid_points(spec.hardpoints, cls)
    _check_shim_support(spec.config, cls)
    return cls(
        name=spec.name,
        version=spec.version,
        units=spec.units,
        hardpoints=_copy_points(spec.hardpoints),
        config=spec.config,
    )


def _build_axle(spec: DoubleWishboneAxleGeometrySpec) -> DoubleWishboneAxleSuspension:
    """
    Build a full axle from per-side corner maps plus shared center points.

    The per-side maps may carry ``DROPLINK_ARB`` (an axle-only point the corner
    class does not accept); it is split out before corner construction. In
    mirror mode the opposite side is generated by reflecting through the XZ
    plane. The config is authored in the vehicle/left frame: the LEFT corner
    takes it verbatim, the RIGHT corner a mirrored copy.
    """
    _check_shim_support(spec.config, DoubleWishboneSuspension)

    blocks = spec.hardpoints
    droplink_arb_points: dict[Side, Point3] = {}

    if blocks.is_explicit:
        assert blocks.left is not None and blocks.right is not None
        side_points: dict[Side, dict[PointKey, Point3]] = {}
        for side, block in ((Side.LEFT, blocks.left), (Side.RIGHT, blocks.right)):
            points = _copy_points(block)
            droplink = points.pop(PointID.DROPLINK_ARB, None)
            if droplink is not None:
                droplink_arb_points[side] = droplink
            _validate_side_signs(points, side)
            side_points[side] = points
    else:
        assert blocks.points is not None
        source_side = blocks.side
        source = _copy_points(blocks.points)
        source_droplink = source.pop(PointID.DROPLINK_ARB, None)
        _validate_side_signs(source, source_side)

        other_side = Side.RIGHT if source_side == Side.LEFT else Side.LEFT
        side_points = {
            source_side: source,
            other_side: _mirror_hardpoints(source),
        }
        if source_droplink is not None:
            droplink_arb_points[source_side] = source_droplink
            droplink_arb_points[other_side] = _mirror_point(source_droplink)

    for side in (Side.LEFT, Side.RIGHT):
        _check_valid_points(side_points[side], DoubleWishboneSuspension)

    center_points = _check_center_points(blocks.center)

    # LEFT gets the config verbatim; RIGHT gets the mirrored copy.
    side_configs = {
        Side.LEFT: spec.config,
        Side.RIGHT: _mirror_config(spec.config),
    }

    corners = {
        side: DoubleWishboneSuspension(
            name=f"{spec.name}_{side.name.lower()}",
            version=spec.version,
            units=spec.units,
            hardpoints=side_points[side],
            config=side_configs[side],
        )
        for side in (Side.LEFT, Side.RIGHT)
    }

    return DoubleWishboneAxleSuspension(
        name=spec.name,
        version=spec.version,
        units=spec.units,
        hardpoints={},
        config=spec.config,
        corners=corners,
        center_points=center_points,
        droplink_arb_points=droplink_arb_points,
    )


# ----------------------------------------------------------------------
# Checks and mirroring helpers
# ----------------------------------------------------------------------

# The shared center block only carries the ARB axis pair.
_VALID_CENTER_POINTS = frozenset({PointID.ARB_AXIS_A, PointID.ARB_AXIS_B})


def _copy_points(points: dict[PointID, Point3]) -> dict[PointKey, Point3]:
    """Copy a point map so built suspensions never alias spec-owned data."""
    return {pid: pos.copy() for pid, pos in points.items()}


def _check_valid_points(
    points: dict[PointKey, Point3], cls: type[Suspension]
) -> None:
    """Reject points the suspension class does not define."""
    unknown = set(points) - set(cls.all_valid_points())
    if unknown:
        names = ", ".join(sorted(p.name for p in unknown))
        raise ValueError(f"Invalid hardpoints for {cls.TYPE_KEY}: {names}")


def _check_shim_support(config: SuspensionConfig, cls: type[Suspension]) -> None:
    """Reject a camber shim config on a type that does not support shims."""
    if config.camber_shim is not None:
        if ShimType.OUTBOARD_CAMBER not in cls.SUPPORTED_SHIMS:
            raise ValueError(
                f"Suspension type '{cls.TYPE_KEY}' does not support "
                "outboard camber shims"
            )


def _check_center_points(center: dict[PointID, Point3]) -> dict[PointID, Point3]:
    """Validate the shared center block (ARB axis points only)."""
    unknown = set(center) - _VALID_CENTER_POINTS
    if unknown:
        names = ", ".join(sorted(p.name for p in unknown))
        raise ValueError(
            f"Unknown center point(s): {names} (expected arb_axis_a/arb_axis_b)."
        )
    return {pid: pos.copy() for pid, pos in center.items()}


def _validate_side_signs(points: dict[PointKey, Point3], side: Side) -> None:
    """
    Check a corner's outboard Y sign matches its declared side.

    LEFT (+Y) requires ``AXLE_OUTBOARD`` Y > 0; RIGHT (-Y) requires Y < 0.
    A missing ``AXLE_OUTBOARD`` is left for the required-point check to report.
    """
    axle_outboard = points.get(PointID.AXLE_OUTBOARD)
    if axle_outboard is None:
        return
    axle_out_y = float(axle_outboard.data[1])
    if side == Side.LEFT and axle_out_y <= 0:
        raise ValueError(
            "Side 'left' requires AXLE_OUTBOARD Y > 0 "
            f"(got {axle_out_y}); check the hardpoint handedness."
        )
    if side == Side.RIGHT and axle_out_y >= 0:
        raise ValueError(
            "Side 'right' requires AXLE_OUTBOARD Y < 0 "
            f"(got {axle_out_y}); check the hardpoint handedness."
        )


def _mirror_point(point: Point3) -> Point3:
    """Reflect a point through the XZ plane (``y -> -y``)."""
    x, y, z = float(point.data[0]), float(point.data[1]), float(point.data[2])
    return Point3([x, -y, z])


def _mirror_hardpoints(
    hardpoints: dict[PointKey, Point3],
) -> dict[PointKey, Point3]:
    """Reflect every hardpoint through the XZ plane."""
    return {pid: _mirror_point(pos) for pid, pos in hardpoints.items()}


def _mirror_config(config: SuspensionConfig) -> SuspensionConfig:
    """
    Mirror a corner config for the opposite side.

    Only the camber shim (if present) carries side-dependent geometry: its face
    datum points are ``y``-negated and the face normal's Y component is negated.
    All other config fields are symmetric and copied verbatim.
    """
    if config.camber_shim is None:
        return config

    shim = config.camber_shim
    normal = shim.shim_face_normal
    mirrored_normal = Direction3(
        [float(normal.data[0]), -float(normal.data[1]), float(normal.data[2])]
    )
    mirrored_shim = shim.model_copy(
        update={
            "shim_face_point_a": _mirror_point(shim.shim_face_point_a),
            "shim_face_point_b": _mirror_point(shim.shim_face_point_b),
            "shim_face_normal": mirrored_normal,
        }
    )
    return config.model_copy(update={"camber_shim": mirrored_shim})
